// Code generated by Kitex v0.9.1. DO NOT EDIT.

package personinfor

import (
	"context"
	person_infor "github.com/cloudwego/biz-demo/gomall/rpc_gen/kitex_gen/person_infor"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	RegisterPersonInfo(ctx context.Context, Req *person_infor.PersonReq, callOptions ...callopt.Option) (r *person_infor.PersonResp, err error)
	GetPersonInfoList(ctx context.Context, Req *person_infor.GetPersonInfoListReq, callOptions ...callopt.Option) (r *person_infor.GetPersonInfoListResp, err error)
	GetPersonInfo(ctx context.Context, Req *person_infor.GetPersonInfoReq, callOptions ...callopt.Option) (r *person_infor.GetPersonInfoResp, err error)
	UpdatePersonInfo(ctx context.Context, Req *person_infor.UpdatePersonInfoReq, callOptions ...callopt.Option) (r *person_infor.UpdatePersonInfoResp, err error)
	DeletePersonInfo(ctx context.Context, Req *person_infor.DeletePersonInfoReq, callOptions ...callopt.Option) (r *person_infor.DeletePersonInfoResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kPersonInforClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kPersonInforClient struct {
	*kClient
}

func (p *kPersonInforClient) RegisterPersonInfo(ctx context.Context, Req *person_infor.PersonReq, callOptions ...callopt.Option) (r *person_infor.PersonResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RegisterPersonInfo(ctx, Req)
}

func (p *kPersonInforClient) GetPersonInfoList(ctx context.Context, Req *person_infor.GetPersonInfoListReq, callOptions ...callopt.Option) (r *person_infor.GetPersonInfoListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetPersonInfoList(ctx, Req)
}

func (p *kPersonInforClient) GetPersonInfo(ctx context.Context, Req *person_infor.GetPersonInfoReq, callOptions ...callopt.Option) (r *person_infor.GetPersonInfoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetPersonInfo(ctx, Req)
}

func (p *kPersonInforClient) UpdatePersonInfo(ctx context.Context, Req *person_infor.UpdatePersonInfoReq, callOptions ...callopt.Option) (r *person_infor.UpdatePersonInfoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdatePersonInfo(ctx, Req)
}

func (p *kPersonInforClient) DeletePersonInfo(ctx context.Context, Req *person_infor.DeletePersonInfoReq, callOptions ...callopt.Option) (r *person_infor.DeletePersonInfoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeletePersonInfo(ctx, Req)
}
