// Code generated by hertz generator.

package person_info

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _personinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _personinfo0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _personinforregisterMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _personinfodeleteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _editMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _personinfoeditMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _personinfo1Mw() []app.HandlerFunc {
	// your code...
	return nil
}
